### ISSUE TITLE
Corrupt particles with RBPF after resampling

### ISSUE THREAD

**Issue by Wehrdo** [MRPT/mrpt#862] opened 2018-11-12 23:10 UTC
When running the rbpf-slam application with `gridmapping_optimal_sampling.ini` as config file and `2006-01ENE-21-SENA_Telecom Faculty_one_loop_only.rawlog` as dataset, when changing the particle filter algorithm to one that includes resampling (pfStandardProposal or pfOptimalProposal), after the resampling step, a memory access exception is thrown.

Many particles in `CMultiMetricMapPDF::m_particles` seem to have corrupt data.

Reproducing this is very consistent, especially if you increase BETA enough so that resampling happens.

**Version**
This is with latest master compiled on MSVC 15.8.7

**Comment by jlblancoc** [comment] 2018-11-13 00:31
Good one! I could reproduce in GCC, so the problem must be in the new resampling algorithm for the "mrpt2" branch. BTW, it's a regression, since in mrpt-1.5 this works nice. 

Will look at it asap. Thanks for the detailed report.

PS: And this is why #714  is so important!

**Comment by jlblancoc** [comment] 2018-11-16 07:35
Fixed now. 
Let us know if you find further issues.

**Closed** 2018-11-16 07:34 UTC
Labels: bug
