### ISSUE TITLE
Errors On OSX

### ISSUE THREAD

**Issue by Gatsby23** [MRPT/mrpt#1116] opened 2020-11-29 12:06 UTC

**Comment by Gatsby23** [comment] 2020-11-29 12:07
When I compile mrpt on my macbook pro, it shows there are something wrong with CschemeArchive.h file, like this:
![image](https://user-images.githubusercontent.com/18000675/100541375-82672d00-327e-11eb-9a0d-0b3635b9b4cf.png)

**Comment by jlblancoc** [comment] 2020-11-30 11:56
Hi, 
What's your system setup? 
- OSX / compiler version
- version of "json", which seems to be installed manually under /usr/local.

**Comment by Gatsby23** [comment] 2020-11-30 12:06
> Hi,
> What's your system setup?
> 
> * OSX / compiler version
> * version of "json", which seems to be installed manually under /usr/local.

![image](https://user-images.githubusercontent.com/18000675/100608415-52379100-3347-11eb-9e6f-5795689336e4.png)
It's the default version of Macos Big Sur, version 11.01
I don't remember what kind of  json  I have installed or not ? How could I check it ?

**Comment by jlblancoc** [comment] 2020-12-01 15:15
I can't directly test builds on a Mac, but here we have CI with an OSX pipeline and it's been building ok for a long time, so there must be something different (a newer/older compiler or json library?). 
Please, run "cmake ." at your build directory and show the "paragraph" after "PLATFORM". For reference, this OSC setup works in CI (look for the "PLATFORM" summary with all the component versions):  https://app.circleci.com/pipelines/github/MRPT/mrpt/1867/workflows/83a12435-5895-4004-a67a-54ca06571cf7/jobs/11254/parallel-runs/0/steps/0-109

**Comment by Gatsby23** [comment] 2020-12-01 15:22
> I can't directly test builds on a Mac, but here we have CI with an OSX pipeline and it's been building ok for a long time, so there must be something different (a newer/older compiler or json library?).
> Please, run "cmake ." at your build directory and show the "paragraph" after "PLATFORM". For reference, this OSC setup works in CI (look for the "PLATFORM" summary with all the component versions): https://app.circleci.com/pipelines/github/MRPT/mrpt/1867/workflows/83a12435-5895-4004-a67a-54ca06571cf7/jobs/11254/parallel-runs/0/steps/0-109
OK, here is my configure list
![image](https://user-images.githubusercontent.com/18000675/100759804-03175c00-342c-11eb-9540-9f40234315f3.png)
![image](https://user-images.githubusercontent.com/18000675/100759838-0ca0c400-342c-11eb-8fb0-144934d1cc47.png)
![image](https://user-images.githubusercontent.com/18000675/100759853-11fe0e80-342c-11eb-985c-2127a76e8e3b.png)

**Comment by jlblancoc** [comment] 2020-12-05 22:42
This was actually caused by #1118, which will be closed by PR #1121 briefly.

**Closed by jlblancoc** 2020-12-05 22:42 UTC
